class CEnv:
    # OpenAI
    OPENAI_API_KEY = "OPENAI_API_KEY"

    # ChromaDB
    CHROMA_DB_DIR = "CHROMA_DB_DIR"

    # AWS
    AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
    AWS_DEFAULT_REGION = "AWS_DEFAULT_REGION"
    AWS_S3_BUCKET = "AWS_S3_BUCKET"

    # Snowflake
    SNOWFLAKE_ACCOUNT = "SNOWFLAKE_ACCOUNT"
    SNOWFLAKE_USER = "SNOWFLAKE_USER"
    SNOWFLAKE_PASSWORD = "SNOWFLAKE_PASSWORD"
    SNOWFLAKE_WAREHOUSE = "SNOWFLAKE_WAREHOUSE"
    SNOWFLAKE_DATABASE = "SNOWFLAKE_DATABASE"
    SNOWFLAKE_SCHEMA = "SNOWFLAKE_SCHEMA"